### PR TITLE
Fix for infinite parser loop at unclosed variable

### LINKED ISSUE #1: [Bug] Parser hangs in infinite loop when variable delimiters are/seem not closed
Using the default delimiter settings, `outline` got stuck in an infinite loop with
```
==> Ref @{0.5}.
```

The parser interprets the dot as the end of the macro call and hangs instead of reporting an error.

I fixed it for Markdown by changing `parser/mod.rs:59ff` (added `else`):
```rust
if let Some(end_index) = input[start_index + start.len()..].find(end) {
    name.push_str(&input[..start_index]);
    name.push_str(&start);
    name.push_str(&end);
    vars.push(
        &input[start_index + start.len()..start_index + start.len() + end_index],
    );
    input = &input[start_index + start.len() + end_index + end.len()..];
} else {
    return Err(ParseError::UnclosedVariableError(orig));
}
```

However, I made other changes, rustfmt reformatted your code, and I feel too inexperienced to make a pull request.

In addition: are you interested in further developing this inspiring piece of work?
I would like to add features like file transclusion, hiding code blocks, excluding blocks from code output, and potentially per-file control over the code destination. So, I ask myself if I should work on a fork, or decouple and just derive from your work.

Currently, I test your tool in combination with the so-called [ODD protocol](https://www.ufz.de/index.php?de=40429) for describing individual-based models: https://github.com/mlange-42/outline/tree/dev/examples/netlogo_odd

Greetings!

### PR DESCRIPTION
**Pull request by mlange-42**
Fix for #1 

"Parser hangs in infinite loop when variable delimiters are/seem not closed"

### CODE REVIEW

File: src/parser/mod.rs [hunk 1]
```diff
@@ -49,6 +49,7 @@ pub trait Parser: ParserConfig {
 
     /// Parses a macro name, returning the name and the extracted variables
     fn parse_name<'a>(&self, mut input: &'a str) -> Result<(String, Vec<&'a str>), ParseError> {
+        let original = input.to_string();
```
Comment (adamreichold) [inline src/parser/mod.rs]: I think it would be better to defer to heap allocation of `.to_string()` by just `Copy`ing the string slice, i.e. `let original = input;` here and `return Err(ParseError::UnclosedVariableError(original.to_owned()));` below, to avoid the overhead in the common case. (Note that shared references `&T` are always `Copy`.) (Also note that `.to_string()` is used to get a stringly-typed representation of some type `T: Display` whereas you already have something stringly-typed and just want an owned version of it, hence `.to_owned()` better expresses the intent here and `.to_string()` doing effectively the same is pretty much coincidence.)

Comment (mlange-42) [reply src/parser/mod.rs]: @adamreichold Thanks, changed accordingly.

**Comment by adamreichold** [comment]
@mlange-42 You seem to have added a bit of trailing whitespace here? Maybe your IDE can remove that for you?

**Comment by mlange-42** [comment]
@adamreichold You mean the "blank" lines that are shown as changes?
Also, it is a bit annoying as I have to turn off rustfmt to not generate a bunch of changes.

**Comment by adamreichold** [comment]
> You mean the "blank" lines that are shown as changes?

Exactly. Most text editors should have a setting to remove those that is independent of actual code formatting for a specific language.

**Review by foxfriends — APPROVED** [review]
